### ISSUE TITLE
No git tags

### ISSUE THREAD

**Issue by rocket-matt** [security-union/yew-actix-template#13]
Hi, and great content btw.

I've noticed that you don't use tags at all that allow people to see just the content that has changed for specific videos.  For example, after watching the first video, I would like to see the code that you used and showed in that video.  Unfortunately, after going to the github link here, I can only see the whole codebase created from ALL the videos.  This makes it difficult to understand what is related to just starting up actix and yew (as seen in video 1) and what is for all the other content in later videos.

Using git tags would allow me to grab a specific version matching the video I am watching.  It would also allow me to diff between versions to see what changed too.

Would it be possible to add tags that synchronise with the released videos on youtube?  Thanks.

**Comment by darioalessandro** [comment]
this is a great idea! I'll share the tag in the video description and the main branch can keep moving.

thanks for this tip!!

**Comment by darioalessandro** [comment]
@rocket-matt we are using tags!!! thank you so much for your suggestion: https://github.com/security-union/zoom-rs/releases/tag/moms-jaw-drops
